### PR TITLE
Fix match() selection, censi

### PR DESCRIPTION
**Pull request by leokoppel**
- Fix switch statement
- Disable a test, todo @Jebediah 
- Simplify Censi inverse. It does change output (making covariance diagonal centimetres instead of  hundreds of metres). I am not sure what the self-adjoint was meant to do before. Another todo for tests.

#### Pre-Merge Checklist:
- [x] Code is documented in doxygen format
- [ ] Code has automated tests
- [x] Zero compiler warnings
- [x] Formatted with `clang-format`

### CODE REVIEW

**Comment by Jebediah** [comment]
The self adjoint thing is a way to specify that the matrix is symmetric

**Comment by leokoppel** [comment]
Does my comment not explain clearly, or is it wrong?

```
        // The covariance is approximately: (Prakhya eqn. 3)
        // d2J_dX2^-1 * d2J_dZdX*cov(z)*d2J_dZdX' *  d2J_dX2^-1
        // = d2J_dX2^-1 * middle * d2J_dX2^-1
        //
        // To get the information matrix, we apply the inverse
```

cov(X) = d2J_dX2^-1 * middle * d2J_dX2^-1
cov(X)^-1 = (d2J_dX2^-1 * middle * d2J_dX2^-1)^-1
cov(X)^-1 = d2J_dX2 * middle^-1 * d2J_dX2

**Comment by leokoppel** [comment]
Oh I see, I did not notice that `d2J_dX2` only contains the top half of d2J/dX2, and selfAdjointView is needed to fill the other half.

**Comment by Jebediah** [comment]
Oh I see. I assumed that because the output was different you changed something. How is the output different now?

**Comment by Jebediah** [comment]
What happens if you put the self adjoint back in but keep the change to the inverse? Does it produce the original output again?

**Comment by leokoppel** [comment]
Yes, it produces the same output (other than numerical error). Will close for now

**Pull request closed without merging**
