### PR TITLE
Expanded reading list of great SLAM papers.

### PR DESCRIPTION
**Pull request by stevenwaslander**
Added a bunch of extra papers based on the partial list that was in there as a place holder.  More to go, but will have to do it in chunks.

### CODE REVIEW

**Comment by stevenwaslander** [comment]
Arun? Or merge?

**Comment by arunxdas** [comment]
LGTM, though I think Andrew Davison's original monoslam paper also deserves to be on the seminal works list

https://scholar.google.com/citations?view_op=view_citation&hl=en&user=A0ae1agAAAAJ&citation_for_view=A0ae1agAAAAJ:u-x6o8ySG0sC

**Comment by stevenwaslander** [comment]
I know there are more, will continue to add as we go through the reading course.  MonoSLAM was definitely an oversight.

**Comment by chutsu** [comment]
Is this ready to be merged in?

**Comment by arunxdas** [comment]
@chutsu I think it's good to merge

**Comment by chutsu** [comment]
ok, merged.

**Pull request merged**
