### PR TITLE
Add gtsam offline VO examples

### PR DESCRIPTION
**Pull request by leokoppel**
_Do not merge; the base is not master_

Add example of offline VO using GTSAM and
- synthetic data
- preprocessed KITTI data

~This is just a starting point. I notice convergence is very sensitive to calibration parameters (?) right now and accuracy is not great. I hope this is an issue with the initialization point, which might be solved by adding intertial factors (later PR).~

You need to have GTSAM installed to build and run these examples. Adding this dependency to travis is left for another PR.

#### Pre-Merge Checklist:
- [x] Code is documented in doxygen format
- [x] Code has automated tests (note: not run on travis due to gtsam dep)
- [x] Zero compiler warnings
- [x] Formatted with `clang-format`

### CODE REVIEW

**Comment by leokoppel** [comment]
Improved with working convergence!

**Comment by cglwn** [comment]
Looks good to me, I'm guessing the bulk of it will be in another PR.

**Comment by leokoppel** [comment]
@cglwn thanks for looking at this, are you able to hit 'approve'?

**Comment by cglwn** [comment]
I don't think I can? I don't have write access I believe. I see the message 
> At least one approved review is required by reviewers with write access. Learn more.

@leokoppel who do I talk to to get write access?

**Comment by arunxdas** [comment]
I sent an invite for James to be added as a member

**Pull request merged**
